--ROLEs de Usuário
DROP ROLE IF EXISTS usr_anon;
CREATE ROLE usr_anon WITH
	LOGIN
	NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT;
    
DROP ROLE IF EXISTS usr_user;
CREATE ROLE usr_user WITH
	LOGIN
	NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT;

DROP ROLE IF EXISTS usr_admin;
CREATE ROLE usr_admin WITH
	LOGIN
	NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT;

--ROLEs de Sistema
DROP ROLE IF EXISTS sys_backup
CREATE ROLE sys_backup WITH
    LOGIN
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT;

DROP ROLE IF EXISTS sys_anon
CREATE ROLE sys_anon WITH
    NOLOGIN
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT;

DROP ROLE IF EXISTS sys_user
CREATE ROLE sys_user WITH
    NOLOGIN
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT;

DROP ROLE IF EXISTS sys_admin
CREATE ROLE sys_admin WITH
    NOLOGIN
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT;

DROP ROLE IF EXISTS sys_maintence
CREATE ROLE sys_maintence WITH
    NOLOGIN
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT;

-- Senhas de Acesso
-- Essa seção será vazia pois as senhas não serão versionadas, obviamente

-- Revogando todas as pemissões da ROLE pública nos schemas criadas
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA system FROM public;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA log FROM public;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA utils FROM public;



