--Permissões das ROLEs do sistema
GRANT CONNECT ON DATABASE gvuedsnndhovbkeuylll TO sys_backup;

GRANT USAGE ON SCHEMA auth TO sys_backup;
GRANT USAGE ON SCHEMA storage TO sys_backup;
GRANT USAGE ON SCHEMA public TO sys_backup;
GRANT USAGE ON SCHEMA log TO sys_backup;
GRANT USAGE ON SCHEMA system TO sys_backup;
GRANT USAGE ON SCHEMA utils TO sys_backup;
GRANT USAGE ON SCHEMA pgbouncer TO sys_backup;
GRANT USAGE ON SCHEMA hdb_catalog TO sys_backup;

GRANT SELECT ON ALL TABLES IN SCHEMA auth TO sys_backup;
GRANT SELECT ON ALL TABLES IN SCHEMA storage TO sys_backup;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO sys_backup;
GRANT SELECT ON ALL TABLES IN SCHEMA log TO sys_backup;
GRANT SELECT ON ALL TABLES IN SCHEMA system TO sys_backup;
GRANT SELECT ON ALL TABLES IN SCHEMA utils TO sys_backup;
GRANT SELECT ON ALL TABLES IN SCHEMA pgbouncer TO sys_backup;
GRANT SELECT ON ALL TABLES IN SCHEMA hdb_catalog TO sys_backup;


GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA auth TO sys_backup;
GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA storage TO sys_backup;
GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA public TO sys_backup;
GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA log TO sys_backup;
GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA system TO sys_backup;
GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA utils TO sys_backup;
GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA hdb_catalog TO sys_backup;
GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA pgbouncer TO sys_backup;